name:           FunCompiler
version:        0.1.0.0
synopsis:       Function Style Compiler In Haskell
license:        GPL-3.0
author:         "ppqwqqq"
github:         "2876225417/FunCompiler"

dependencies:   
  - base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  FunCompiler-exe:
    main:             Main.hs
    source-dirs:      app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - FunCompiler
