name:           FunCompiler
version:        0.1.0.0
synopsis:       Function Style Compiler In Haskell
license:        GPL-3.0
author:         "ppqwqqq"
github:         "2876225417/FunCompiler"

dependencies:   
  - base >= 4.20.0.0 && < 5.0.0.0

library:
  source-dirs: src

  exposed-modules:
    - FunCompiler.Lexer 
    - FunCompiler.Parser
    - FunCompiler.AST

executables:
  FunCompiler-exe:
    main:             Main.hs
    source-dirs:      app
    ghc-options:
      - -threaded 
      - -rtsopts 
      - -with-rtsopts=-N 
    dependencies:
      - FunCompiler

tests:
  FunCompiler-test:
    main: Spec.hs 
    source-dirs: tests 
    ghc-options:
      - -threaded 
      - -rtsopts 
      - -with-rtsopts=-N 
    dependencies:
      - FunCompiler
      - hspec
